# This is a basic workflow to help you get started with Actions

name: PDF Analyzer
# Controls when the workflow will run

env: 
  DOCUMENT_URL: http://hobokennj.iqm2.com/Citizens/FileOpen.aspx?Type=1&ID=1756
  # As per MuckRock Documentation, Document Cloud username and password must be stored with this name https://github.com/MuckRock/documentcloud-alert-cron-addon 
  DC_USERNAME: ${{ secrets.DOCUMENT_CLOUD_USERNAME }}
  DC_PASSWORD: ${{ secrets.DOCUMENT_CLOUD_PASSWORD }}

on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  schedule:
#    - cron: "15 * * * *"
  push:
    branches:
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  downloadPDF:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.6'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Download a PDF using URL 
        run: curl "$DOCUMENT_URL" -o output.pdf

      - name: Execute Python Script
        run: python upload.py

